version: "3.4"

services:
  
  mssqldata:
    image: microsoft/mssql-server-linux:latest
    networks: 
      - sqlservernet
    entrypoint: /bin/bash

  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: ec-aswmoderna-mssql
    hostname: mssqls-server
    networks: 
      - sqlservernet
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      # we copy our scripts onto the container
      - ./:/usr/src/app 
    # bash will be executed from that path, our scripts folder
    working_dir: /usr/src/app 
    # run the entrypoint.sh that will import the data AND sqlserver
    command: bash -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EmergingB00king@2019
      DATABASE_NAME: EmergingBooking
    # don't use this if you don't want to persit data between docker up and down
    volumes_from:
      - mssqldata

networks:
  sqlservernet: